sudo: false

language: php

php:
    - "hhvm"

before_script:
    - composer install --prefer-source

script:
    - hhvm -v Eval.Jit=false bin/hackunit test/ --exclude test/Fixtures/ --exclude test/Mocks/
